import { jsPDF } from 'jspdf';
import { GeneratedImage } from '../types';

export const generateBookPdf = (childName: string, theme: string, images: GeneratedImage[]) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Cover Page
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(40);
  doc.setTextColor(50, 50, 80);
  
  const title = `Coloring Book`;
  const subTitle = `for ${childName}`;
  const themeText = `Theme: ${theme}`;

  doc.text(title, pageWidth / 2, 80, { align: 'center' });
  
  doc.setFontSize(30);
  doc.setTextColor(236, 72, 153); // Pinkish
  doc.text(subTitle, pageWidth / 2, 100, { align: 'center' });

  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(themeText, pageWidth / 2, 130, { align: 'center' });

  doc.setFontSize(12);
  doc.text("Generated by DreamColor AI", pageWidth / 2, pageHeight - 20, { align: 'center' });

  // Image Pages
  images.forEach((img, index) => {
    doc.addPage();
    
    // Add a border
    doc.setLineWidth(1);
    doc.setDrawColor(200, 200, 200);
    doc.rect(10, 10, pageWidth - 20, pageHeight - 20);

    // Add Image
    // Aspect ratio of A4 is approx 210x297.
    // Our images are 3:4.
    // Let's fit them nicely within margins.
    const margin = 20;
    const availableWidth = pageWidth - (margin * 2);
    const availableHeight = pageHeight - (margin * 2);
    
    // Calculate dimensions to maintain aspect ratio (3:4)
    const imgRatio = 3/4;
    let finalW = availableWidth;
    let finalH = availableWidth / imgRatio;

    if (finalH > availableHeight) {
      finalH = availableHeight;
      finalW = finalH * imgRatio;
    }

    const x = (pageWidth - finalW) / 2;
    const y = (pageHeight - finalH) / 2;

    doc.addImage(img.url, 'PNG', x, y, finalW, finalH);
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${index + 1} - ${theme}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  });

  doc.save(`${childName.replace(/\s+/g, '_')}_Coloring_Book.pdf`);
};